version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-react"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/app-flask"
    schedule:
      interval: "daily"
    labels:
      - "python"
      - "dependencies"